# This netlify.toml file is for the documentation site living under /docs

[build]
  base = "docs"
  publish = "site"
  command = "mkdocs build"

[build.environment]
  PYTHON_VERSION = "3.6"
  # NODE_OPTIONS = "--max_old_space_size=4096"
  # NODE_VERSION = "10.16.3"
  # RUBY_VERSION = "2.6.2"
