description: Performs a deployment using a fork
parameters:
  network:
    type: string
steps:
  - cmd-fork-start:
      network: << parameters.network >>
      reset: true
  - run: node publish deploy --use-fork --yes --network << parameters.network >>
  - persist_to_workspace:
      root: .
      paths:
        - publish/deployed
        - .db
