description: Prepares contract artifacts and deployed/<network>/config.json for a deployment using a fork based on releases.json
parameters:
  network:
    type: string
steps:
  - run: node publish build
  - run: node publish prepare-deploy --network << parameters.network >>
  - persist_to_workspace:
      root: .
      paths:
        - build
        - publish/deployed
