import tests.test_Court
import tests.test_Deploy
import tests.test_ERC20Token
import tests.test_ERC20FeeToken
import tests.test_EtherNomin
import tests.test_FeeCollection
import tests.test_Havven
import tests.test_HavvenEscrow
import tests.test_Owned
import tests.test_SafeDecimalMath
import tests.test_Upgrade
