jobs:
  - prepare
  - lint:
      requires:
        - prepare
  - test-contracts:
      requires:
        - prepare
  - test-contracts-legacy:
      requires:
        - prepare
  - test-ovm:
      requires:
        - prepare
  - test-publish:
      requires:
        - prepare
  - test-deployments:
      requires:
        - prepare
  - test-local:
      requires:
        - prepare
  - pack:
      requires:
        - prepare
  - coverage-report:
      requires:
        - prepare
  - gas-report:
      requires:
        - prepare
  - slither:
      requires:
        - prepare
  # ~~~~~~~~~~~~~~~ KOVAN ~~~~~~~~~~~~~~~ #
  - test-kovan:
      requires:
        - prepare
      filters:
        branches:
          only: staging
  # ~~~~~~~~~~~~~~~ RINKEBY ~~~~~~~~~~~~~~~ #
  - test-rinkeby:
      requires:
        - prepare
      filters:
        branches:
          only: staging
  # ~~~~~~~~~~~~~~~ MAINNET ~~~~~~~~~~~~~~~ #
  - test-mainnet:
      requires:
        - prepare
      filters:
        branches:
          only: master
  # ~~~~~~~~~~~~~~~ ROPSTEN ~~~~~~~~~~~~~~~ #
  # Ropsten paused (see above).
