jobs:
  - prepare:
      filters:
        branches:
          only: develop
  # ~~~~~~~~~~~~~~~ MAINNET ~~~~~~~~~~~~~~~ #
  - fork-prepare-deploy:
      name: fork-prepare-deploy-mainnet
      network: mainnet
      requires:
        - prepare
  - fork-deploy:
      name: fork-deploy-mainnet
      network: mainnet
      requires:
        - fork-prepare-deploy-mainnet
  - fork-test-prod:
      name: fork-test-prod-mainnet
      network: mainnet
      requires:
        - fork-deploy-mainnet
  # ~~~~~~~~~~~~~~~ RINKEBY ~~~~~~~~~~~~~~~ #
  - fork-prepare-deploy:
      name: fork-prepare-deploy-rinkeby
      network: rinkeby
      requires:
        - prepare
      filters:
        branches:
          only: develop
  - fork-deploy:
      name: fork-deploy-rinkeby
      network: rinkeby
      requires:
        - fork-prepare-deploy-rinkeby
      filters:
        branches:
          only: develop
  - fork-test-prod:
      name: fork-test-prod-rinkeby
      network: rinkeby
      requires:
        - fork-deploy-rinkeby
      filters:
        branches:
          only: develop
  # ~~~~~~~~~~~~~~~ KOVAN ~~~~~~~~~~~~~~~ #
  - fork-prepare-deploy:
      name: fork-prepare-deploy-kovan
      network: rinkeby
      requires:
        - prepare
      filters:
        branches:
          only: develop
  - fork-deploy:
      name: fork-deploy-kovan
      network: rinkeby
      requires:
        - fork-prepare-deploy-kovan
      filters:
        branches:
          only: develop
  - fork-test-prod:
      name: fork-test-prod-kovan
      network: rinkeby
      requires:
        - fork-deploy-kovan
      filters:
        branches:
          only: develop
  # ~~~~~~~~~~~~~~~ ROPSTEN ~~~~~~~~~~~~~~~ #
  # Ropsten paused (see above).
