triggers:
  - schedule:
      cron: "0 0 * * *"
      filters:
        branches:
          only:
            - master
jobs:
  - job-prepare

  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  # Deployment validation
  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - job-validate-deployments:
      requires:
        - job-prepare

  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  # Production tests
  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - job-prod-tests:
      name: job-prod-tests-mainnet
      network: mainnet
      requires:
        - job-prepare
  - job-prod-tests:
      name: job-prod-tests-rinkeby
      network: rinkeby
      requires:
        - job-prepare
  - job-prod-tests:
      name: job-prod-tests-kovan
      network: kovan
      requires:
        - job-prepare

  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  # Differential local production tests
  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - job-diff-prod-tests-local:
      name: job-diff-prod-tests-local
      requires:
        - job-prepare
  - job-diff-prod-tests-local-ovm:
      name: job-diff-prod-tests-local-ovm
      requires:
        - job-prepare
