jobs:
  - job-prepare:
      filters:
        branches:
          only: /.*(staging|master).*/

  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  # Packaging
  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - job-pack-browser:
      filters:
        branches:
          only: /.*(staging|master).*/
      requires:
        - job-prepare

  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  # Deployment validation
  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - job-validate-deployments:
      filters:
        branches:
          only: /.*(staging|master).*/
      requires:
        - job-prepare

  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  # Production tests
  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - job-prod-tests:
      name: job-prod-tests-mainnet
      filters:
        branches:
          only: /.*(staging|master).*/
      network: mainnet
      requires:
        - job-prepare
  - job-prod-tests:
      name: job-prod-tests-rinkeby
      filters:
        branches:
          only: /.*(staging|master).*/
      network: rinkeby
      requires:
        - job-prepare
  - job-prod-tests:
      name: job-prod-tests-kovan
      filters:
        branches:
          only: /.*(staging|master).*/
      network: kovan
      requires:
        - job-prepare

  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  # Differential local production tests
  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - job-diff-prod-tests-local:
      name: job-diff-prod-tests-local
      filters:
        branches:
          only: /.*(staging|master).*/
      requires:
        - job-prepare
  - job-diff-prod-tests-local-ovm:
      name: job-diff-prod-tests-local-ovm
      filters:
        branches:
          only: /.*(staging|master).*/
      requires:
        - job-prepare

  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  # Differential production tests
  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - job-diff-prod-tests:
      name: job-diff-prod-tests-mainnet
      filters:
        branches:
          only: /.*(staging|master).*/
      network: mainnet
      requires:
        - job-prepare
  - job-diff-prod-tests:
      name: job-diff-prod-tests-rinkeby
      filters:
        branches:
          only: /.*(staging|master).*/
      network: rinkeby
      requires:
        - job-prepare
  - job-diff-prod-tests:
      name: job-diff-prod-tests-kovan
      filters:
        branches:
          only: /.*(staging|master).*/
      network: kovan
      requires:
        - job-prepare
