jobs:
  - job-prepare:
      {{> filter-staging.yml}}

  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  # Packaging
  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - job-pack-browser:
      {{> filter-staging.yml}}
      {{> require-prepare.yml}}

  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  # Deployment validation
  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - job-validate-deployments:
      {{> filter-staging.yml}}
      {{> require-prepare.yml}}

  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  # Production tests
  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - job-prod-tests:
      name: job-prod-tests-mainnet
      network: mainnet
      {{> filter-staging.yml}}
      {{> require-prepare.yml}}

  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  # Differential local production tests
  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - job-diff-prod-tests-local:
      name: job-diff-prod-tests-local
      {{> filter-staging.yml}}
      {{> require-prepare.yml}}
  - job-diff-prod-tests-local-ovm:
      name: job-diff-prod-tests-local-ovm
      {{> filter-staging.yml}}
      {{> require-prepare.yml}}

  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  # Differential production tests
  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - job-diff-prod-tests:
      name: job-diff-prod-tests-mainnet
      network: mainnet
      {{> filter-staging.yml}}
      {{> require-prepare.yml}}
