jobs:
  - job-prepare:
      filters:
        branches:
          only: develop
  # ~~~~~~~~~~~~~~~ MAINNET ~~~~~~~~~~~~~~~ #
  - job-fork-prepare-deploy:
      name: job-fork-prepare-deploy-mainnet
      network: mainnet
      requires:
        - job-prepare
  - job-fork-deploy:
      name: job-fork-deploy-mainnet
      network: mainnet
      requires:
        - job-fork-prepare-deploy-mainnet
  - job-fork-test-prod:
      name: job-fork-test-prod-mainnet
      network: mainnet
      requires:
        - job-fork-deploy-mainnet
  # ~~~~~~~~~~~~~~~ RINKEBY ~~~~~~~~~~~~~~~ #
  - job-fork-prepare-deploy:
      name: job-fork-prepare-deploy-rinkeby
      network: rinkeby
      requires:
        - job-prepare
      filters:
        branches:
          only: develop
  - job-fork-deploy:
      name: job-fork-deploy-rinkeby
      network: rinkeby
      requires:
        - job-fork-prepare-deploy-rinkeby
      filters:
        branches:
          only: develop
  - job-fork-test-prod:
      name: job-fork-test-prod-rinkeby
      network: rinkeby
      requires:
        - job-fork-deploy-rinkeby
      filters:
        branches:
          only: develop
  # ~~~~~~~~~~~~~~~ KOVAN ~~~~~~~~~~~~~~~ #
  - job-fork-prepare-deploy:
      name: job-fork-prepare-deploy-kovan
      network: rinkeby
      requires:
        - job-prepare
      filters:
        branches:
          only: develop
  - job-fork-deploy:
      name: job-fork-deploy-kovan
      network: rinkeby
      requires:
        - job-fork-prepare-deploy-kovan
      filters:
        branches:
          only: develop
  - job-fork-test-prod:
      name: job-fork-test-prod-kovan
      network: rinkeby
      requires:
        - job-fork-deploy-kovan
      filters:
        branches:
          only: develop
  # ~~~~~~~~~~~~~~~ ROPSTEN ~~~~~~~~~~~~~~~ #
  # Ropsten paused (see above).
