jobs:
  - job-prepare:
      filters:
        branches:
          only: /.*(master).*/
  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  # Etherscan validations
  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  # NOTE: This is currently disabled because the script used to validate etherscan
  # verifications cannot handle multiple ABIs for the same source.
  # - job-validate-etherscan:
  #     name: job-validate-etherscan-mainnet
  #     filters:
  #       branches:
  #         only: /.*(master).*/
  #     network: mainnet
  #     requires:
  #       - job-prepare
  # - job-validate-etherscan:
  #     name: job-validate-etherscan-rinkeby
  #     filters:
  #       branches:
  #         only: /.*(master).*/
  #     network: rinkeby
  #     requires:
  #       - job-prepare
  # - job-validate-etherscan:
  #     name: job-validate-etherscan-kovan
  #     filters:
  #       branches:
  #         only: /.*(master).*/
  #     network: kovan
  #     requires:
  #       - job-prepare
  # - job-validate-etherscan:
  #     name: job-validate-etherscan-ropsten
  #     filters:
  #       branches:
  #         only: /.*(master).*/
  #     network: ropsten
  #     requires:
  #       - job-prepare
