jobs:
  - job-prepare:
      filters:
        branches:
          only: /.*(master).*/
  # ~~~~~~~~~~~~ Etherscan validation on MAINNET ~~~~~~~~~~~~~
  - job-validate-etherscan:
      name: job-validate-etherscan-mainnet
      filters:
        branches:
          only: /.*(master).*/
      network: mainnet
      requires:
        - job-prepare
  # ~~~~~~~~~~~~ Etherscan validation on RINKEBY ~~~~~~~~~~~~~
  - job-validate-etherscan:
      name: job-validate-etherscan-rinkeby
      filters:
        branches:
          only: /.*(master).*/
      network: rinkeby
      requires:
        - job-prepare
  # ~~~~~~~~~~~~ Etherscan validation on KOVAN ~~~~~~~~~~~~~
  - job-validate-etherscan:
      name: job-validate-etherscan-kovan
      filters:
        branches:
          only: /.*(master).*/
      network: kovan
      requires:
        - job-prepare
  # ~~~~~~~~~~~~ Etherscan validation on ROPSTEN ~~~~~~~~~~~~~
  - job-validate-etherscan:
      name: job-validate-etherscan-ropsten
      filters:
        branches:
          only: /.*(master).*/
      network: ropsten
      requires:
        - job-prepare
