working_directory: ~/repo
docker:
  - image: circleci/node:12.18
resource_class: xlarge
steps:
  - checkout
  - attach_workspace:
      at: .
  - run: NODE_OPTIONS=--max_old_space_size=4096 npm run coverage
  - run: bash <(curl -s https://codecov.io/bash)
