working_directory: ~/repo
docker:
  - image: circleci/node:12.18
    auth:
      username: $DOCKERHUB_USERNAME
      password: $DOCKERHUB_TOKEN
parameters:
  network:
    type: string
steps:
  - checkout
  - attach_workspace:
      at: .
  - fork_prepare_deploy:
      network: << parameters.network >>
