working_directory: ~/repo
docker:
  - image: circleci/node:12.18
parameters:
  network:
    type: string
steps:
  - checkout
  - attach_workspace:
      at: .
  - fork_test_prod:
      network: << parameters.network >>
