# Builds a testing chain which is used for integration tests and downstream projects
{{> job-header-machine.yml}}
steps:
  # get foundry
  - restore_cache:
      keys:
        - foundry-bin-${foundry_locked_commit}-14
  - rust/install: {}
  - run: |
      if [ ! -d ~/.foundry ]; then
        curl -L https://foundry.paradigm.xyz | bash
        echo 'export PATH="$PATH:$HOME/.foundry/bin"' >> ~/.bashrc
        source ~/.bashrc
        foundryup
      fi
      echo 'export PATH="$PATH:$HOME/.foundry/bin"' >> ~/.bashrc
      source ~/.bashrc

  - save_cache:
      key: foundry-bin-${foundry_locked_commit}-14
      paths:
        - ~/.foundry/bin

  - checkout
  - attach_workspace:
      at: .
  - run: npx hardhat compile --optimizer --fail-oversize
  - run: node publish build --test-helpers
  - run: npx hardhat --network cannon cannon:build cannonfile.aggregator.toml
  - run: npx hardhat --network cannon cannon:build
  - persist_to_workspace:
      root: .
      paths:
        - build
        - cannon
        - publish/deployed
