# Simulates a deployment in a local chain, and runs production tests against it
working_directory: ~/repo
docker:
  - image: circleci/node:12.18
steps:
  - checkout
  - attach_workspace:
      at: .
  # Compile
  - run: node publish build
  # Start local chain
  - cmd-local-start
  # Deploy
  - run: node publish deploy --network local --fresh-deploy --yes
  # Run production tests
  - run: npm run test:prod -- --patch-fresh-deployment
