# Validates deployment json data against on-chain data
working_directory: ~/repo
docker:
  - image: circleci/node:12.18
parameters:
  network:
    type: string
steps:
  - checkout
  - attach_workspace:
      at: .
  - run: npm run test:deployments
