working_directory: ~/repo
docker:
  - image: circleci/node:12.18
steps:
  - checkout
  - attach_workspace:
      at: .
  - cmd-testnet-pvt:
      network: rinkeby
  - cmd-etherscan-check:
      network: rinkeby
