# Simulates a deployment of an ovm configuration in a local chain, and runs production tests against it
working_directory: ~/repo
docker:
  - image: circleci/node:12.18
steps:
  - checkout
  - attach_workspace:
      at: .
  # Compile
  - run: node publish build
  # Start local chain
  - cmd-local-start
  # Deploy
  - run: node publish deploy --network local --fresh-deploy --private-key 0xc5e8f61d1ab959b397eecc0a37a6517b8e67a0e7cf1f4bce5591f3ed80199122 --yes --use-ovm --ignore-safety-checks --ignore-custom-parameters --deployment-path ./publish/deployed/local-ovm
  # Run production tests
  - run: npm run test:prod -- --deployment-path ./publish/deployed/local-ovm
