# Simulates a deployment in a fork, and runs production tests against it
{{> job-header.yml}}
parameters:
  network:
    type: string
steps:
  - checkout
  - attach_workspace:
      at: .
  # Compile
  - run: node publish build
  # Start fork
  - cmd-fork-start:
      network: << parameters.network >>
      reset: true
  # Prepare deploy
  - run: node publish prepare-deploy --network << parameters.network >>
  # Deploy
  - run: node publish deploy --add-new-synths --use-fork --yes --network << parameters.network >>
  # Run production tests
  - run: npm run test:prod:gas -- --patch-fresh-deployment && npx codechecks codechecks.prod.yml
  - store_artifacts:
      path: test-gas-used-prod.log
