# Runs all unit and spec tests
{{> job-header.yml}}
resource_class: large
steps:
  - checkout
  - attach_workspace:
      at: .
  - run: npx hardhat compile --showsize --optimizer
  - run:
      name: Test and output gas used
      command: |
        set +e
        npm test
        EXIT_CODE=$?
        cat test-gas-used.log
        printf "\\n"
        exit $EXIT_CODE
