# Builds a testing chain which is used for integration tests and downstream projects
{{> job-header-machine.yml}}
steps:
  # get foundry
  - restore_cache:
      keys:
        - foundry3
  - rust/install: {}
  - run: curl -O https://raw.githubusercontent.com/foundry-rs/foundry/master/foundryup/foundryup && chmod +x ./foundryup
  - run: ./foundryup -r usecannon/foundry
  - run: rm -rf *
  - run: echo 'export PATH="$PATH:$HOME/.foundry/bin"' >> $BASH_ENV
  - save_cache:
      key: foundry3
      paths:
        - ~/.cargo
        - ~/.foundry

  - checkout
  - attach_workspace:
      at: .
  - run: npx hardhat compile --optimizer --fail-oversize
  - run: node publish build --test-helpers
  - run: npx hardhat cannon:build --file cannonfile.aggregator.toml
  - run: npx hardhat cannon:build
  - persist_to_workspace:
      root: .
      paths:
        - build
        - cannon
        - publish/deployed