# Runs all unit and spec tests
{{> job-header-node.yml}}
resource_class: large
parallelism: 8
steps:
  - checkout
  - attach_workspace:
      at: .
  - run: npx hardhat compile --showsize --optimizer
  - run:
      name: Test and output gas used
      command: |
        set +e
        circleci tests glob 'test/contracts/*.js' |
        circleci tests split |
        xargs npm test -- --gas
        EXIT_CODE=$?
        printf "\\n"
        exit $EXIT_CODE
  - run:
      name: Save gas report
      command: |
        mv gasReporterOutput.json ./gasReporterOutput-$CIRCLE_NODE_INDEX.json
  - persist_to_workspace:
      root: .
      paths:
        - gasReporterOutput-*.json
  - run: npm install
  - run: mkdir ~/junit
  - run:
      command: mocha test --reporter mocha-junit-reporter
      environment:
        MOCHA_FILE: ~/junit/test-results.xml
      when: always
  - store_test_results:
      path: ~/junit
  - store_artifacts:
      path: ~/junit
