# Validates deployment json data against on-chain data
{{> job-header.yml}}
steps:
  - checkout
  - attach_workspace:
      at: .
  - run:
      name: Only run when publish/deployed/*/deployment.json changes
      command: |
        changes=$(git diff --name-status origin/develop | grep 'publish\/deployed\/[a-z0-9\-]*\/deployment\.json$' || true)
        if [ -z "$changes" ]; then
          circleci-agent step halt
        fi;
  - run: npm run test:deployments
