working_directory: ~/repo
docker:
  - image: circleci/node:12.18
    auth:
      username: $DOCKERHUB_USERNAME
      password: $DOCKERHUB_TOKEN
steps:
  - checkout
  - restore_cache:
      keys:
        - 'v2-dependencies-{{ checksum "package-lock.json" }}'
  - run: npm install
  - save_cache:
      key: 'v2-dependencies-{{ checksum "package-lock.json" }}'
      paths:
        - node_modules
  - persist_to_workspace:
      root: .
      paths:
        - node_modules
