docker:
  - image: trailofbits/eth-security-toolbox
steps:
  - checkout
  - attach_workspace:
      at: .
  - run:
      name: Show Slither output
      # ignore slither error codes
      command: |
        set +e
        slither .
        exit 0
