working_directory: ~/repo
docker:
  - image: circleci/node:12.18
resource_class: large
steps:
  - checkout
  - attach_workspace:
      at: .
  - run: npm run compile:legacy
  - run: npx buidler test:legacy
