working_directory: ~/repo
docker:
  - image: circleci/node:12.18
steps:
  - checkout
  - attach_workspace:
      at: .
  - testnet_pvt:
      network: rinkeby
  - etherscan_check:
      network: rinkeby
