working_directory: ~/repo
docker:
  - image: circleci/node:12.18
resource_class: large
steps:
  - checkout
  - attach_workspace:
      at: .
  - run: npx buidler compile --showsize --optimizer
  - run:
      name: Test and output gas used
      command: |
        set +e
        npm test
        EXIT_CODE=$?
        cat test-gas-used.log
        printf "\\n"
        exit $EXIT_CODE
