working_directory: ~/repo
docker:
  - image: circleci/node:12.18
    auth:
      username: $DOCKERHUB_USERNAME
      password: $DOCKERHUB_TOKEN
steps:
  - checkout
  - attach_workspace:
      at: .
  - run: npm run test:deployments
