working_directory: ~/repo
docker:
  - image: circleci/node:12.18
    auth:
      username: $DOCKERHUB_USERNAME
      password: $DOCKERHUB_TOKEN
steps:
  - checkout
  - attach_workspace:
      at: .
  - run:
      name: Compile in OVM, enforcing size limit
      command: |
        npx buidler compile --ovm --optimizer
