working_directory: ~/repo
docker:
  - image: circleci/node:12.18
steps:
  - checkout
  - attach_workspace:
      at: .
  - run:
      name: Compile in OVM, enforcing size limit
      command: |
        npx buidler compile --ovm --optimizer
