working_directory: ~/repo
docker:
  - image: circleci/node:12.18
    auth:
      username: $DOCKERHUB_USERNAME
      password: $DOCKERHUB_TOKEN
resource_class: large
steps:
  - checkout
  - attach_workspace:
      at: .
  - run: npm run compile:legacy
  - run: npx buidler test:legacy
